### ISSUE TITLE
AttributeError: module 'portion.interval' has no attribute 'empty'

### ISSUE THREAD

**Issue by fredrikaverpil** [AlexandreDecan/portion#82]
Hi 👋  and thanks for your hard work on this project!

I noticed I had a large amount of tests failing after updating from 2.3.1 to 2.4.0, with this error.

```python
>       intervals = portion.interval.empty()
E       AttributeError: module 'portion.interval' has no attribute 'empty'
```

Is this expected?

Also, would you please confirm that the better syntax should be `intervals = portion.Interval()` to get an empty interval?

**Comment by AlexandreDecan** [comment]
Hello, 

The various helpers to create intervals have been moved from `portion.interval` to `portion.func`. This is an internal change that should not have affected your code. Sorry ;-) These helpers should be accessed using the public API (i.e., `portion.empty()`). As a general rule, your code should only use the `portion` module, not its submodules ;)

**Comment by fredrikaverpil** [comment]
Great, thanks for this clarification. 👍
